name: Release

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.msg), 'Publish')"

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set Git Author
        run: |
          git config --global user.email "ficsit-bot@nevir.net"
          git config --global user.name "Ficsit Bot"

      - name: Release
        run: yarn release
